### ISSUE TITLE
Support BrazeKit 8.0.1

### ISSUE THREAD

**Issue by danieltai** [Tealium/tealium-ios-braze-remote-command#19]
BrazeKit has an [update to their privacy manifest in 8.0.1](https://github.com/braze-inc/braze-swift-sdk/releases/tag/8.0.1). Could you please update this SDK to support BrazeKit `~> 8.0`?

**Comment by craigrouse** [comment]
@danieltai very sorry for not responding to this - we didn't get a notification for some reason. This has now been resolved in release 3.3.0.
