### ISSUE TITLE
Upgrade Braze to 9.3.0

### ISSUE THREAD

**Issue by p4checo** [Tealium/tealium-ios-braze-remote-command#22]
Hi there 👋🏼 

As the title suggests, can you please update this to support the latest Braze 9.3.0 version (or latest if any)? Thanks 🙏🏼

**Comment by craigrouse** [comment]
@p4checo We'll get this prioritised and reply when it's done.

**Comment by jameskeith** [comment]
@p4checo - this should now be available in the latest release  - [v3.4.0](https://github.com/Tealium/tealium-ios-braze-remote-command/releases/tag/3.4.0)
